name: Prueba_CI_CD

on:
  push

jobs:
  Ejecutar_script:
    runs-on: self-hosted
    steps:        
    - name: Hacer print
      run: |
        echo $(python3 --version)

    # - name: Correr script
    #   run: |
    #     python Download.py
