name: Prueba_CI_CD

on:
  push

jobs:
  Pruebas:
    runs-on: self-hosted
    steps:        
    - name: Ver cosas del server
      run: |
        # python3 --version
        cd && cd Pruebas
        pwd
        
    # - name: HACER PULL
    #   run: |
    #     python envio_correo.py
