name: Prueba_CI_CD

on:
  push

jobs:
  Pruebas:
    runs-on: self-hosted
    steps:        
    - name: Ver cosas del server
      run: |
        # python3 --version
        cd && cd Pruebas  ### OJO!! CADA PASO ES INDEPENDIENTE, EN CADA PASO DEBO CAMBIAR AL DIR DESEADO!
        pwd   
        
    - name: Enviar cambios al server
      run: |
        cd && cd Pruebas/Training
        # git config --global user.email "actions@github.com"
        # git config --global user.name "GitHub Actions"
        git pull
