name: Prueba_CI_CD

on:
  push

jobs:
  Pruebas:
    runs-on: self-hosted
    steps:        
    - name: Ver cosas del server
      run: |
        echo $(pwd)
        echo $(ls)
        echo $(python3 --version)
        
    # - name: Correr script
    #   run: |
    #     python envio_correo.py
