name: Prueba_CI_CD

on:
  push

jobs:
  Ejecutar_script:
    runs-on: self-hosted
    steps:        
    - name: Ver cosas del print
      run: |
        pwd
        ls
        echo $(python3 --version)
        
    # - name: Correr script
    #   run: |
    #     python envio_correo.py
